- lib/data/data/starbucks_desserts.json
- 스타벅스 디저트 관련 Mock 데이터 생성했습니다.
> feat : 스타벅스 디저트 목데이터 생성

- .github/workflows/flutter_test.yml
- lib/core/widgets/payment/dialog_action_button.dart
- lib/core/widgets/payment/dialog_cancel_button.dart
- lib/core/widgets/payment/order_summary_box.dart
- lib/core/widgets/payment/payment_method_tile.dart
- 다이얼로그 취소, 액션 버튼
- 주문내역 박스
- 결제 선택 박스
- Closes #이슈번호
> feat : payment 관련 위젯 구성

- lib/home_screen.dart
- test : issue 자동 close 연습
closes #33
> test : issue 자동 close 연습

- lib/home_screen.dart
- test : 자동으로 issue close연습
- Closes #36
> test : 자동으로 issue close연습

- lib/data/data/drink_mock_data.json
> chore : drink mock data 추가

- lib/core/widgets/kiosk/menu_bottom_bar.dart
- lib/core/widgets/kiosk/menu_card.dart
- lib/core/widgets/payment/order_summary_box.dart
- lib/data/mapper/order_to_cart_mapper.dart
- lib/view/cart/cart_notifier.dart
- lib/view/cart/cart_state.dart
- lib/view/main_menu/menu_select_screen.dart
> 메뉴선택 화면과 장바구니 화면 연동

- lib/core/widgets/kiosk/first_select_category.dart
- lib/core/widgets/kiosk/menu_bottom_bar.dart
- lib/view/cart/cart_notifier.dart
- lib/view/cart/cart_screen.dart
- lib/view/home_screen.dart
- lib/view/payment/payment_screen.dart
- lib/view/payment/payment_success_screen.dart
- 장바구니 테마 오류 수정 
- 장바구니 보존 오류 수정
> fix : 장바구니 테마 오류 수정 & feat : 장바구니 보존 오류 수정

- lib/core/router/router.dart
- lib/core/widgets/kiosk/menu_card.dart
> fix : import error fix

- lib/core/router/router.dart
- lib/core/widgets/kiosk/menu_card.dart
- lib/view/ingredinet_select/ingredient_selector.dart
- lib/view/main_menu/menu_select_screen.dart
- lib/view/menu_set_select/set_select_screen.dart
- lib/view/select_set_menu/select_set_menu_screen.dart
- lib/view/set_builder/set_builder_screen.dart
- 각 파트 별로 나뉘어져 있던 각 페이지들을 연결
- 각 파트 별 기능이 연동되게 설정
- Closes #이슈번호
> feat : 페이지 연결

- lib/core/widgets/kiosk/menu_card.dart
- lib/core/widgets/payment/total_amount.dart
- 메뉴카드에서 천단위마다 콤마를 추가해 금액 보기 쉽게 변경
> menu_card에서 천단위마다 콤마 추가

- lib/core/widgets/kiosk/menu_bottom_sheet.dart
- lib/view/main_menu/menu_select_screen.dart
- 햄버거와 커피 선택 외에 카테고리에서 선택시 BottomSheet를 출력해 어떤 메뉴를 선택했는지 알려줌으로 가시성을 높임
- 불필요한 중복된 코드 제거
> 햄버거나 커피 외에 메뉴 선택시 BottomSheet출력

- lib/core/widgets/menu/burger_card.dart
- lib/view/set_builder/set_builder_screen.dart
> fix : set선택시 메인 메뉴 이름 overflow발생 문제 해결

- lib/core/widgets/kiosk/menu_bottom_bar.dart
- lib/core/widgets/payment/payment_method_tile.dart
- lib/view/cart/cart_screen.dart
- lib/view/home_screen.dart
- lib/view/installment_select/installment_screen.dart
- lib/view/kiosk_start_page/kiosk_start_page.dart
- lib/view/main_menu/menu_select_screen.dart
- lib/view/payment/payment_screen.dart
- lib/view/payment/payment_success_screen.dart
- lib/view/place_select/place_select_screen.dart
> feat : 스크린 리더 접근성 개선

- android/app/src/main/AndroidManifest.xml
- lib/view/ingredinet_select/ingredient_selector.dart
- lib/view/menu_set_select/set_select_screen.dart
- lib/view/payment/payment_success_screen.dart
- lib/view/set_builder/set_builder_notification.dart
- lib/view/set_builder/set_builder_screen.dart
- lib/view/set_builder/set_builder_state.dart
- macos/Runner/Release.entitlements
- pubspec.yaml
- shorebird.yaml
> feat : shorebird 기능 추가 

- lib/core/router/router.dart
- lib/view/order_complete/order_complete_screen.dart
- lib/view/payment/payment_success_screen.dart
- 진동벨 번호 확인 스크린 추가
- Closes #101
> feat : 진동벨 번호 확인 스크린 추가

- ios/Runner.xcodeproj/project.pbxproj
- lib/core/widgets/payment/installment_group.dart
- lib/view/installment_select/installment_screen.dart
> feat : 결제하기 화면 스크롤 오버 수정

- lib/core/widgets/payment/installment_group.dart
- lib/view/installment_select/installment_screen.dart
> feat : 스크롤 오버 수정

- lib/core/models/debounce.dart
- lib/core/services/menu_service.dart
- lib/view/ingredinet_select/ingredient_notifier.dart
- lib/view/main_menu/menu_select_screen.dart
- lib/view/menu_set_select/set_select_screen.dart
- lib/view/set_builder/set_builder_notification.dart
- pubspec.yaml
- throttle을 활용해 bottomsheet가 연속으로 출력되는것을 방지함
- import 된 사용하지 않는 패키지 제거
> feat : throttle로 bottomsheet출력 방식 변경

- lib/view/main_menu/menu_select_screen.dart
- [x} 제목은 한눈에 이해할 수 있게 작성
- throttle 방식을 통한 속도 조절
> fix : bottomsheet 딜레이 조절

- lib/view/menu_set_select/set_select_screen.dart
- lib/view/set_builder/set_builder_notification.dart
> fix setPage

- lib/view/ingredinet_select/ingredient_selector.dart
- lib/view/menu_set_select/set_select_notifier.dart
- lib/view/menu_set_select/set_select_screen.dart
- lib/view/menu_set_select/set_select_state.dart
> fix : 세트 선택 이후 버튼 및 장바구니 초기화 오류 수정
